/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.steam_do_paraguai.view;

/**
 *
 * @author lukas-freitas
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        
        LojaPanel loja = new LojaPanel();
        loja.setSize(708,368);
        loja.setLocation(0,0);
        
        template.removeAll();
        template.add(loja);
        template.validate();
        template.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundoPanel = new javax.swing.JPanel();
        barraSuperiorPanel = new javax.swing.JPanel();
        steamLabel = new javax.swing.JLabel();
        bibliotecaButton = new javax.swing.JButton();
        carrinhoButton = new javax.swing.JButton();
        lojaButton = new javax.swing.JButton();
        iniciarSessaoButton = new javax.swing.JButton();
        fundosButton = new javax.swing.JButton();
        template = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(720, 480));
        setMinimumSize(new java.awt.Dimension(720, 480));

        fundoPanel.setBackground(new java.awt.Color(62, 122, 155));

        barraSuperiorPanel.setBackground(new java.awt.Color(30, 30, 29));
        barraSuperiorPanel.setForeground(new java.awt.Color(30, 30, 30));

        steamLabel.setFont(new java.awt.Font("Cascadia Code", 0, 30)); // NOI18N
        steamLabel.setForeground(new java.awt.Color(255, 255, 255));
        steamLabel.setText("STEAM DO PARAGUAI");

        bibliotecaButton.setBackground(new java.awt.Color(30, 30, 29));
        bibliotecaButton.setForeground(new java.awt.Color(255, 255, 255));
        bibliotecaButton.setText("BIBLIOTECA");
        bibliotecaButton.setBorder(null);
        bibliotecaButton.setBorderPainted(false);
        bibliotecaButton.setContentAreaFilled(false);
        bibliotecaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bibliotecaButtonActionPerformed(evt);
            }
        });

        carrinhoButton.setBackground(new java.awt.Color(30, 30, 29));
        carrinhoButton.setForeground(new java.awt.Color(255, 255, 255));
        carrinhoButton.setText("CARRINHO");
        carrinhoButton.setBorder(null);
        carrinhoButton.setBorderPainted(false);
        carrinhoButton.setContentAreaFilled(false);
        carrinhoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carrinhoButtonActionPerformed(evt);
            }
        });

        lojaButton.setBackground(new java.awt.Color(30, 30, 29));
        lojaButton.setForeground(new java.awt.Color(255, 255, 255));
        lojaButton.setText("LOJA");
        lojaButton.setBorder(null);
        lojaButton.setBorderPainted(false);
        lojaButton.setContentAreaFilled(false);
        lojaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lojaButtonActionPerformed(evt);
            }
        });

        iniciarSessaoButton.setBackground(new java.awt.Color(30, 30, 29));
        iniciarSessaoButton.setFont(new java.awt.Font("Cascadia Code", 0, 24)); // NOI18N
        iniciarSessaoButton.setForeground(new java.awt.Color(255, 255, 255));
        iniciarSessaoButton.setText("INICIAR SESSAO");
        iniciarSessaoButton.setBorder(null);
        iniciarSessaoButton.setBorderPainted(false);
        iniciarSessaoButton.setContentAreaFilled(false);
        iniciarSessaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSessaoButtonActionPerformed(evt);
            }
        });

        fundosButton.setBackground(new java.awt.Color(30, 30, 29));
        fundosButton.setForeground(new java.awt.Color(255, 255, 255));
        fundosButton.setText("FUNDOS");
        fundosButton.setBorder(null);
        fundosButton.setBorderPainted(false);
        fundosButton.setContentAreaFilled(false);

        javax.swing.GroupLayout barraSuperiorPanelLayout = new javax.swing.GroupLayout(barraSuperiorPanel);
        barraSuperiorPanel.setLayout(barraSuperiorPanelLayout);
        barraSuperiorPanelLayout.setHorizontalGroup(
            barraSuperiorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraSuperiorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(barraSuperiorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(barraSuperiorPanelLayout.createSequentialGroup()
                        .addComponent(lojaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bibliotecaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraSuperiorPanelLayout.createSequentialGroup()
                        .addComponent(steamLabel)
                        .addGap(53, 53, 53)))
                .addGroup(barraSuperiorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(barraSuperiorPanelLayout.createSequentialGroup()
                        .addComponent(carrinhoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fundosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(iniciarSessaoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        barraSuperiorPanelLayout.setVerticalGroup(
            barraSuperiorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraSuperiorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(barraSuperiorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iniciarSessaoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(steamLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(barraSuperiorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lojaButton)
                    .addComponent(bibliotecaButton)
                    .addComponent(carrinhoButton)
                    .addComponent(fundosButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout templateLayout = new javax.swing.GroupLayout(template);
        template.setLayout(templateLayout);
        templateLayout.setHorizontalGroup(
            templateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        templateLayout.setVerticalGroup(
            templateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout fundoPanelLayout = new javax.swing.GroupLayout(fundoPanel);
        fundoPanel.setLayout(fundoPanelLayout);
        fundoPanelLayout.setHorizontalGroup(
            fundoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraSuperiorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(fundoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(template, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        fundoPanelLayout.setVerticalGroup(
            fundoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoPanelLayout.createSequentialGroup()
                .addComponent(barraSuperiorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(template, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarSessaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSessaoButtonActionPerformed
        LoginPanel log = new LoginPanel();
        log.setSize(708,368);
        log.setLocation(0,0);
        
        template.removeAll();
        template.add(log);
        template.revalidate();
        template.repaint();
    }//GEN-LAST:event_iniciarSessaoButtonActionPerformed

    private void bibliotecaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bibliotecaButtonActionPerformed
        BibliotecaPanel bib = new BibliotecaPanel();
        bib.setSize(708,368);
        bib.setLocation(0,0);
        
        template.removeAll();
        template.add(bib);
        template.revalidate();
        template.repaint();
    }//GEN-LAST:event_bibliotecaButtonActionPerformed

    private void lojaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lojaButtonActionPerformed
        LojaPanel loja = new LojaPanel();
        loja.setSize(708,368);
        loja.setLocation(0,0);

        template.removeAll();
        template.add(loja);
        template.validate();
        template.repaint();
    }//GEN-LAST:event_lojaButtonActionPerformed

    private void carrinhoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carrinhoButtonActionPerformed
        CarrinhoPanel carrinho = new CarrinhoPanel();
        carrinho.setSize(708,368);
        carrinho.setLocation(0,0);

        template.removeAll();
        template.add(carrinho);
        template.validate();
        template.repaint();
    }//GEN-LAST:event_carrinhoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraSuperiorPanel;
    private javax.swing.JButton bibliotecaButton;
    private javax.swing.JButton carrinhoButton;
    private javax.swing.JPanel fundoPanel;
    private javax.swing.JButton fundosButton;
    private javax.swing.JButton iniciarSessaoButton;
    private javax.swing.JButton lojaButton;
    private javax.swing.JLabel steamLabel;
    private javax.swing.JPanel template;
    // End of variables declaration//GEN-END:variables
}
